# Site settings
title: The Humble Programmer
email: ironcev@hotmail.com
url: "http://thehumbleprogrammer.com"
shorturl: "http://thehumbleprogrammer.com"
permalink: /:title/
offlineMode: false
disqusShortname: thehumbleprogrammer

# Build settings
markdown: kramdown

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Igor Rončević"
      showComments: true
      showSocialSharing: true
      hasCode: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "Igor Rončević"
      showComments: false
      showSocialSharing: false
      hasCode: false

#Compress HTML
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]