# Site settings
title: The Humble Programmer
email: ironcev@hotmail.com
description: >
baseurl: ""
url: "http://thehumbleprogrammer.com"
permalink: /:title/
offlineMode: true
disqusShortname: thehumbleprogrammer
# Build settings
markdown: kramdown
# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Igor Rončević"
      showComments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "Igor Rončević"
      showComments: false